# Generated by Django 3.1.1 on 2020-09-05 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentator', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=10000)),
                ('comment_time', models.DateTimeField(null=True)),
                ('serial_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.blog')),
            ],
        ),
    ]
