# Generated by Django 3.1.1 on 2020-09-05 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='serial_number',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
